// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PublishNotifier
{
    internal sealed partial class Vsix
    {
        public const string Id = "763d21f2-0b6e-49d1-ac3c-bd3a74e78566";
        public const string Name = "Publish Notifier";
        public const string Description = @"Notify your team in Slack or HipChat when you Deploy a Web Project Using One-Click Publish from Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Dalibor Mesarić";
        public const string Tags = "slack, microsoft teams, teams, publish, notification";
    }
}
